info:
  title: MGM 媽閣塘項目API
  version: 1.0.0
  description: |
    This is API documentation for MGM 媽閣塘項目
openapi: 3.0.0
servers:
  - url: https://api.example.com
    description: Production server
  - url: https://testapi.example.com
    description: Test server
paths:
  # Merchant
  /merchant/list:
    get:
      tags:
        - '03 BW管理後台'
        - Merchant 商家
      summary: 商家列表. list merchants
      description: 商家列表. list merchants
      parameters:
        - in: query
          name: id
          description: 商家ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: merchant
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Merchant'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Option Set
  /merchant/data/{id}:
    get:
      tags:
        - '01 商圈雲Saas'
        - '03 BW管理後台'
        - Merchant 商家
      summary: 商家詳細資訊. get merchant data
      description: 商家詳細資訊. get merchant data
      parameters:
        - in: path
          name: id
          description: 商家ID.
          schema:
            type: number
          required: true 
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Merchant'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
    put:
      tags:
        - '01 商圈雲Saas'
        - '03 BW管理後台'
        - Merchant 商家
      summary: 商家更新. update merchant
      description: 商家更新. update merchant
      parameters:
        - in: path
          name: id
          description: 商家ID.
          schema:
            type: number
          required: true 
          example: 1
      requestBody:
        description: 商家資料
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 商家電郵地址.
                  type: string
                  format: email
                phone:
                  description: 商家電話.
                  type: string
                password:
                  description: 商家密碼.
                  type: string
                firstName:
                  description: 商家名字.
                  type: string
                lastName:
                  description: 商家姓氏.
                  type: string
                locale:
                  description: 商家使用語言.
                  type: string
              example:
                email: user@example.com
                phone: 1234567890
                password: password
                firstName: John
                lastName: Doe

  /merchant/findByPhone:
    get:
      tags:
        - '01 商圈雲Saas'
        - Merchant 商家
      summary: 用手機號碼獲取商家詳細資訊. get merchant data by phone
      description: 用手機號碼獲取商家詳細資訊. get merchant data by phone
      parameters:
        - in: query 
          name: phone
          description: 商家手機號碼.
          schema:
            type: number
          required: true 
          example: 1234567890
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Merchant'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
  /merchant/register:
    post:
      tags:
        - '01 商圈雲Saas'
        - Merchant 商家
      summary: 商家註冊. merchant registration
      description: 商家註冊. merchant registration
      requestBody:
        description: 商家資料
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 商家電郵地址.
                  type: string
                  format: email
                phone:
                  description: 商家電話.
                  type: string
                password:
                  description: 商家密碼.
                  type: string
                  format: password
                firstName:
                  description: 商家名字.
                  type: string
                lastName:
                  description: 商家姓氏.
                  type: string
                locale:
                  description: 商家使用語言.
                  type: string
                  enum:
                    - en
                    - zh-TW
                    - zh-CN
                toc:
                  description: 商家同意條款.
                  type: bool
              required:
                - email
                - phone
                - password
                - firstName
                - lastName
                - locale
                - toc
              example:
                email: user@example.com
                phone: 123456789
                password: password
                firstName: John
                lastName: Doe
                locale: en
                toc: true
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Merchant'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Validation Request
  /merchant/resetPassword:
    post:
      tags:
        - '01 商圈雲Saas'
        - Merchant 商家
      summary: 商家重置密碼. merchant reset password
      description: 商家重置密碼. merchant reset password
      requestBody:
        description: 商家資料
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  description: 商家ID.
                  type: number
                password:
                  description: 商家密碼.
                  type: string
                  format: password
                code:
                  description: 手機接收之4位數字驗證碼.
                  type: string
              required:
                - id
                - password
                - code
              example:
                id: 1
                password: password
                code: 1234
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Merchant'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Validation Code
  /validation/request:
    post:
      tags:
        - '01 商圈雲Saas'
        - '03 BW管理後台'
        - Validation 手機驗證碼
      summary: 發送手機驗證碼.send Mobile Validation Code.
      description: 發送手機驗證碼. send Mobile Validation Code.
      requestBody:
        description: 商家資料
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetType:
                  description: 發送SMS對象類型.
                  type: string
                  enum:
                    - merchant
                    - customer
                targetId:
                  description: 發送SMS對象Id. 可以是商家ID或用戶ID
                  type: number
              required:
                - targetType 
                - targetId
              example:
                targetType: merchant
                targetId: 1
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                    description: 驗證碼ID
                  status: 
                    type: string
                    enum:
                      - failure
                      - sent
                      - pending
                      - success
                    description: 驗證碼發送狀態
                required:
                  - id
                  - status
                example:
                  id: 1234
                  status: sent
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  /validation/confirm:
    post:
      tags:
        - '01 商圈雲Saas'
        - Validation 手機驗證碼
      summary: 手機驗證碼驗證. Mobile Validation Code Confirm
      description: 手機驗證碼驗證. Mobile Validation Code Confirm
      requestBody:
        description: 商家資料及驗證碼
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetType:
                  description: 發送SMS對象類型.
                  type: string
                  enum:
                    - merchant
                    - customer
                targetId:
                  description: 發送SMS對象Id.
                  type: number
                code:
                  description: 驗證碼.
                  type: string
              required:
                - targetType
                - targetId
                - code
              example:
                targetType: merchant
                targetId: 1
                code: 1234
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                    description: 驗證碼ID
                  status: 
                    type: string
                    description: 驗證狀態
                required:
                  - id
                  - status
                example:
                  id: 1234
                  status: success
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  /optionset/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - OptionSet 選項集
      description: 選項集列表. list option sets
      summary: 選項集列表. list option sets
      parameters:
        - in: query
          name: id
          description: 選項集系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: optionset
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/OptionSet'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
  /optionset/data/{id}:
    get: 
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - OptionSet 選項集
      description: 獲取選項集. get option sets
      summary: 獲取集列表. get option sets
      parameters:
        - in: path
          name: id
          description: 選項集系統ID.
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/OptionSet'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
    put:
      tags:
        - '01 商圈雲Saas'
        - OptionSet 選項集
      description: 更新選項集. get option sets
      summary: 更新選項集. get option sets
      parameters:
        - in: path
          name: id
          description: 選項集系統ID.
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/OptionSet'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'




  # Item API
  /item/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Item 商品
      summary: 商品列表. list items
      description: 商品列表. list items
      parameters:
        - in: query
          name: id
          description: 商品系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: item
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  /items/data/{id}:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Item 商品
      summary: 商品詳細資訊. get item data
      description: 商品詳細資訊. get item data
      parameters:
        - in: path
          name: id
          description: 商品系統ID.
          required: true
          schema:
            type: number
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Item'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Attributes API
  /attribute/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Attribute 商品屬性 
      description: 列出商品屬性. list item attributes
      summary: 列出商品屬性. list item attributes
      parameters:
        - in: query
          name: id
          description: 商品屬性系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: attribute
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Attribute'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
            
  /attribute/data/{id}:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Attribute 商品屬性 
      description: 獲取商品屬性. get item attributes
      summary: 獲取商品屬性. get item attributes
      parameters:
        - in: path
          name: id
          description: 商品屬性系統ID.
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                      $ref: '#/components/schemas/Attribute'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
    put:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Attribute 商品屬性 
      description: 更新商品屬性. update item attributes
      summary: 更新商品屬性. update item attributes
      parameters:
        - in: path
          name: id
          description: 商品屬性系統ID.
          schema:
            type: number
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attribute'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                      $ref: '#/components/schemas/Attribute'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Category API
  /category/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Category 商品分類
      summary: 列出商品分類. list item category 
      description: 列出商品分類. list item category 
      parameters:
        - in: query
          name: id
          description: 商品分類系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          name: name
          description: 商品分類名稱.
          schema:
            type: string
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: category
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # ModifierSet API
  /category/data/{id}:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Category 商品分類
      summary: 獲取商品分類. get item category 
      description: 獲取商品分類. get item category 
      parameters:
        - in: path
          name: id
          description: 商品分類系統ID.
          schema:
            type: number
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Category'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'
    put:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Category 商品分類
      summary: 更新商品分類. update item category 
      description: 更新商品分類. update item category 
      parameters:
        - in: path
          name: id
          description: 商品分類系統ID.
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Category'
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'


  # ModifierSet API
  /modifierset/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Modifier 商品配料集
      summary: 商品配料集. list item modifier sets
      description: 商品配料集. list item modifier sets
      parameters:
        - in: query
          name: id
          description: 商品配料集系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          name: name
          description: 商品配料集名稱.
          schema:
            type: string
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: modifierset
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ModifierSet'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Image API
  /image/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - Image 圖片庫
      summary: 列出圖片. get Images
      description: 列出圖片. get Images
      parameters:
        - in: query
          name: id
          description: 圖片系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: category
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Image'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

  # Store API
  /store/list:
    get:
      tags:
        - '01 商圈雲Saas'
        - '02 商圈雲POS'
        - '04 商圈APP'
        - Store 門市
      summary: 列出門市. list Stores
      description: 列出門市. list Stores
      parameters:
        - in: query
          name: id
          description: 門市系統ID.
          schema:
            type: array
            items:
              type: number
            explode: true
            style: form
        - in: query
          $ref: '#/components/parameters/limitParam'
        - in: query
          $ref: '#/components/parameters/offsetParam'
      responses:
        "200":
          description: 200 response
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: category
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Store'
                  hasMore:
                    type: boolean
                required:
                  - object
                  - data
                  - hasMore
        "404":
          $ref: '#/components/responses/404NotFound'
        "403":
          $ref: '#/components/responses/403Forbidden'

components:

  # Reusable parameters
  parameters:
    offsetParam:
      name: offset
      in: query
      description: 起始數據筆數. the offset of starting record
      required: false
      schema:
        type: number
        default: 0

    limitParam:
      name: limit
      in: query
      description: 顯示數據筆數. the number of records to show
      required: false
      schema:
        type: number
        default: 30

  # Reusable response
  responses:
    404NotFound:
      description: 404 response
      content:
        text/html; charset=UTF-8:
          schema:
            type: object
            properties:
              status:
                type: boolean
                default: false
              error:
                type: string
                default: "Not Found"

    403Forbidden:
      description: 403 response
      content:
        application/json; charset=UTF-8:
          schema:
            type: object
            properties:
              status:
                type: boolean
                default: false
              error:
                type: string

  schemas:
    Image:
      type: object
      description: |
        圖片. Image 
      properties:
        id:
          type: number
          description: |
            圖片系統ID. Image ID
        name:
          type: string
          description: |
            圖片名稱. Image name
        url:
          type: string
          description: |
            圖片URL. Image URL
        size:
          type: number
          description: |
            圖片大小. Image size
        createdAt:
          type: number
          description: |
            圖片創建時間 timestamp. Image created timestamp
      required:
        - name
        - url
        - size
      example:
        id: 1
        name: logo
        url: https://example.com/logo.png
        size: 123
        createdAt: 1600000000

    Store:
      type: object
      description: |
        門市. Store
      properties:
        id:
          type: number
          description: |
            門市系統ID. Store ID
        name:
          type: string
          description: |
            門市名稱. Location name
        createdAt:
          type: number
          description: |
            門市創建時間 timestamp. Location created timestamp
      required:
        - name
      example:
        id: 1
        name: home
        createdAt: 1600000000

    Option:
      type: object
      description: |
        選項. Option
      properties:
        name:
          type: string
          description: |
            選項名稱. Option name
        color:
          type: string
          pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'
          description: |
            選項顏色. Option color in hex format
      required:
        - name
        - color
      example:
        name: Red
        color: "#FF0000"

    OptionSet:
      type: object
      description: |
        選項集. Option set
      properties:
        id:
          type: number
          description: |
            選項集系統ID. Option set ID
        name:
          type: string
          description: |
            選項集名稱. Option set name
        type:
          type: string
          enum:
            - text
            - textColor
        options:
          type: array
          description: |
            可用選項. Options available
          items:
            $ref: '#/components/schemas/Option'
      required:
        - id
        - name
        - type
        - options
      example:
        id: 1
        name: Color
        type: text
        options: [{"color": "#FF0000", "name": "Red"}, {"color": "#00FF00", "name": "Green"}, {"color": "#0000FF", "name": "Blue"}]

    Unit:
      type: object
      description: |
        單位. Unit
      properties:
        id:
          type: number
          description: |
            單位系統ID. Unit ID
        name:
          type: string
          description: |
            單位名稱. Unit name
        decimal:
          type: string
          enum:
            - '1'
            - '.0'
            - '.00'
            - '.000'
            - '.0000'
            - '.00000'
          description: |
            小數點位數. Decimal places
        custom:
          type: boolean
          description: |
            是否為自定義單位. Is it a custom unit
      required:
        - id
        - name
        - decimal
        - custom
      example:
        id: 1
        name: kg
        decimal: '.0'
        custom: false


    Item:
      type: object
      properties:
        id:
          type: number
          description: |
            商品系統ID. Item Id
        name:
          type: string
          description: |
            商品名稱. Item name
        categoryId:
          type: number
          description: |
            商品分類系統ID. Item Category ID
        category:
          $ref: '#/components/schemas/Category'
        description:
          type: string
          description: |
            商品描述. Item description
        images:
          type: array
          description: |
            商品圖片. Item images
          items:
            $ref: '#/components/schemas/Image'
        Locations:
          type: array
          description: |
            商品上架地點. Item on stock locations
          items:
            $ref: '#/components/schemas/Store'
        sku:
          type: string
          description: |
            商品SKU. Item SKU
        unit:
          $ref: '#/components/schemas/Unit'
        price:
          type: number
          description: |
            商品價格. Item price
        weight:
          type: number
          description: |
            商品重量. Item weight
        tracking:
          type: boolean
          description: |
            是否開啟追蹤. Is tracking enabled
        lowStockAlert:
          type: boolean
          description: |
            是否開啟低庫存警示. Is low stock alert enabled
        lowStockAmount:
          type: number
          description: |
            低庫存警示數量. Low stock alert threshold
        variations:
          type: array
          description: |
            商品規格. Item variations
          items:
            $ref: '#/components/schemas/Variation'
        attributes:
          type: array
          description: |
            商品屬性. Item attributes
          items:
            $ref: '#/components/schemas/AttributeValue'
      required:
        - id
        - name
        - categoryId

    #Variation
    Variation:
      allOf:
        - $ref: '#/components/schemas/Item'
        - type: object
          properties:
            parentId:
              type: number
              description: |
                父商品系統ID. Parent Item ID
          required:
            - parentId

    #Attribute
    Attribute:
      type: object
      properties:
        id:
          type: number
          description: |
            商品屬性系統ID. Attribute ID
        slug:
          type: string
          description: |
            屬性名稱. Attribute slug
        name:
          type: string
          description: |
            屬性顯示名稱. Attribute display name
        type:
          type: string
          description: |
            屬性類型. Attribute type
          enum:
            - text
            - toggle
            - number
            - selection
        multiple:
          type: boolean
          description: |
            是否為多選. Is it multiple
        options:
          type: array
          description: |
            屬性選項. Attribute options
          items:
            $ref: '#/components/schemas/Option'
        decimal:
          type: string
          enum:
            - '1'
            - '.0'
            - '.00'
            - '.000'
            - '.0000'
            - '.00000'
          description: |
            小數點位數. Decimal places
      required:
        - id
        - slug
        - name
        - type
      example:
        id: 1
        slug: color
        name: Color
        type: text
        multiple: false
        options: [{"color": "#FF0000", "name": "Red"}, {"color": "#00FF00", "name": "Green"}, {"color": "#0000FF", "name": "Blue"}]
        decimal: '.0'

    #AttributeValue
    AttributeValue:
      type: object
      properties:
        name:
          type: string
          description: |
            屬性名稱. Attribute slug
        value:
          type: string
          description: |
            屬性值. Attribute value
      required:
        - name
        - value
      example:
        name: Color
        value: Red

    #Modifier:
    Modifier:
      type: object
      properties:
        id:
          type: number
          description: |
            配料系統ID. Modifier ID
        name:
          type: string
          description: |
            配料名稱. Modifier name
        image:
          description: |
            配料圖片. Modifier image
          $ref: '#/components/schemas/Image'
        price:
          type: number
          description: |
            配料價錢. Modifier price
        status:
          type: boolean
          description: |
            是否啟用. Is it enabled
      required:
        - id
        - name
        - price
        - status
      example:
        id: 1
        name: Spicy
        image: https://example.com/spicy.png
        price: 10
        status: true

    # Modifier Set
    ModifierSet:
      type: object
      properties:
        id:
          type: number
          description: |
            配料集系統ID. Modifier set ID
        name:
          type: string
          description: |
            配料集名稱. Modifier set name
        multiple:
          type: boolean
          description: |
            是否為多選. Is it multiple
        modifiers:
          type: array
          description: |
            配料集可選配料. Modifiers in modifier set
          items:
            $ref: '#/components/schemas/Modifier'
        Locations:
          type: array
          description: |
            配料集可選地點. Locations in modifier set
          items:
            $ref: '#/components/schemas/Store'
      example:
        id: 1
        name: Spicy
        multiple: false
        modifiers: [{"id": 1, "name": "Spicy", "image": "https://example.com/spicy.png", "price": 10, "status": true}]
        Locations: [{"id": 1, "name": "Macau"}]

    # Category
    Category:
      type: object
      properties:
        id:
          type: number
          description: |
            分類系統ID. Category ID
        name:
          type: string
          description: |
            分類名稱. Category name
      required:
        - id
        - name
      example:
        id: 1
        name: Food

    Merchant:
      type: object
      properties:
        id: 
          type: number
          description: |
            商家系統ID. Merchant ID
        name: 
          type: string
          description: |
            商家名稱. Merchant name
        email:
          description: 商家電郵地址.
          type: string
          format: email
        phone:
          description: 商家電話.
          type: string
        password:
          description: 商家密碼.
          type: string
          format: password
        firstName:
          description: 商家名字.
          type: string
        lastName:
          description: 商家姓氏.
          type: string
        locale:
          description: 商家使用語言.
          type: string
          enum:
            - en
            - zh-TW
            - zh-CN
        industryId:
          description: 商家所屬行業.
          type: number
        Industry:
          $ref: '#/components/schemas/Industry'
        businessSize:
          type: string
          enum:
            - '1-10'
            - '11-50'
            - '51-100'
            - '100+'
        BusinessServe:
          type: array
          items: 
            $ref: '#/components/schemas/BusinessServe'
        toc:
          description: 商家同意條款.
          type: bool
      required:
        - id
        - name
      example:
        id: 1
        name: ABC Company
        email: user@example.com
        phone: 1234567890
        firstName: John
        lastName: Doe
        locale: en
        toc: true
        industryId: 1
        Industry: {"id": 1, "name": "Food & Beverage"}
        businessSize: "1-10"
        BusinessServe: [{"id": 1, "name": "Lunch Box"}, {"id":2, "name": "Beverage"}]


    # Industry
    Industry:
      type: object
      properties:
        id:
          type: number
          description: |
            行業系統ID. Industry ID
        name:
          type: string
          description: |
            行業名稱. Industry name
      required:
        - id
        - name
      example:
        id: 1
        name: Food & Beverage

    # BusinessServe 
    BusinessServe:
      type: object
      properties:
        id:
          type: number
          description: |
            公司服務系統ID. BusinessServe ID
        name:
          type: string
          description: |
            公司服務或商品名稱. BusinessServe name
      required:
        - id
        - name
      example:
        id: 1
        name: Food & Beverage

    # Validation
    Validation:
      type: object
      properties:
        id:
          type: number
          description: |
            驗證碼ID. Validation ID
        code:
          type: string
          description: |
            4位數字驗證碼. Validation Code
        targetType:
          type: string
          description: |
            發送對象類型. Target type
          enum:
            - customer
            - merchant
        targetId:
          type: number
          description: |
            發送對象ID. Target ID
        status:
          type: string
          enum: 
            - failure
            - sent
            - pending
            - success
          description: |
            驗證碼狀態. Validation status
        expiredAt:
          type: number
          description: |
            驗證碼過期時間. Validation expired timestamp(5分鐘後到期)
        createdAt:
          type: number
          description: |
            驗證碼創建時間. Validation created timestamp
      required:
        - id
        - code
        - targetType 
        - targetId
        - status
        - expiredAt
      example:
        id: 1
        code: 1234
        targetType: merchant
        targetId: 1
        status: sent
        expiredAt: 1664605900
        createdAt: 1664605600

    Customer:
      type: object
      properties:
        id: 
          type: number
          description: |
            顧客系統ID. Customer ID
        name: 
          type: string
          description: |
            顧客名稱. Customer name
        email:
          description: 顧客電郵地址.
          type: string
          format: email
        phone:
          description: 顧客電話.
          type: string
        password:
          description: 顧客密碼.
          type: string
          format: password
        companyName:
          description: 顧客公司名稱.
          type: string
        birthday:
          description: 顧客生日 timestamp
          type: number
        lastOrderAt:
          description: 顧客最後訂單時間.
          type: number
        purchaseCount:
          description: 顧客訂購次數.
          type: number
        purchaseAmount:
          description: 顧客訂購總金額.
          type: number

    Supplier:
      type: object
      properties:
        id: 
          type: number
          description: |
            供應商系統ID. Supplier ID
        name: 
          type: string
          description: |
            供應商名稱. Supplier name
        email:
          description: 供應商電郵地址.
          type: string
          format: email
        phone:
          description: 供應商電話.
          type: string
        contactName:
          description: 聯繫人名稱.
          type: string
        lastOrderAt:
          description: 供應商最後訂單時間.
          type: number
        purchaseCount:
          description: 供應商訂購次數.
          type: number
        purchaseAmount:
          description: 供應商訂購總金額.
          type: number

    Order:
      type: object
      properties:
        id:
          type: number
          description: |
            訂單系統ID. Order ID
        type:
          type: string
          enum:
            - sale
            - saleReturn
            - purchase
            - purchaseReturn
          description: |
            訂單類型. Order type
        targetType:
          type: string
          description: |
            發送對象類型. Target type
          enum:
            - customer
            - supplier
          default: customer
        targetId:
          type: number
          description: |
            發送對象ID. Target ID
          default: -1
        Target:
          oneOf:
            - $ref: '#/components/schemas/Customer'
            - $ref: '#/components/schemas/Supplier'
        createdAt:
          type: number
          description: |
            訂單創建時間. Order created timestamp
        OrderItems:
          type: array
          description: |
            訂單商品. Order items
          items: 
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      properties:
        id:
          type: number
          description: |
            訂單商品系統ID. Order Item ID
        orderId:
          type: number
          description: |
            訂單系統ID. Order ID
        itemId:
          type: number
          description: |
            商品系統ID. Item ID
        variationId:
          type: number
          description: |
            商品規格系統ID. Variation ID
        quantity:
          type: number
          description: |




